language: ruby
rvm:
- 2.0.0
before_install:
- gem update --system
- gem --version
- gem install sass
- npm install
- npm install -g bower
- bower install
before_script:
- bundle exec rake travis:decrypt_config
- gulp build
script:
- gulp test
- bundle exec rspec test/ruby
after_success:
- bundle exec rake travis:deploy
env:
  global:
    secure: k6PBGTMYj/N5KPbMwAVnlrkyDknudw9MJK/sNTspodJAZPmcIaHcWKgbURhGj2IQBsEObHnX6wpbfGs1iNHqEBiA8PeenxcoHkivsMpbzDUcp9xa7GRU0D+eERyzws9wg1MB4ALgdyorIP6V2yKjEpl8r1iOWcePmNgf93ec0iY=
notifications:
  slack:
    secure: HsMnZomfPeLQNIjFGoVRK+9YnIHD0PFNsL/Se+2L7li0sjQzaVZ+EEohGT+Ph5oFq5uitmdoCxmWPIZJrk5Y083ZiJMkuoLzqta+IgzfvOVeWG+ctgb5aiESAbUWfDJKWgi7SlWicQ7/8MmqCt4JLIIMmBhBZfGQQPLIjOfyNOg=
