language: ruby

rvm:
  - 2.0.0

before_install:
  - gem install sass
  - npm install
  - npm install -g bower
  - bower install

before_script:
  - gulp build
  
script:
  - gulp test

after_script:
  - gulp build